# Generated by Django 5.0.7 on 2024-08-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_department_reporting_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='reporting_manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
