# Generated by Django 5.0.7 on 2024-08-19 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0006_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='location',
        ),
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.AddField(
            model_name='document',
            name='document_file',
            field=models.FileField(default='default_files/placeholder.pdf', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('adhar_card', 'Aadhaar Card'), ('graduate_certificate', 'Graduate Certificate'), ('experience_letter', 'Experience Letter'), ('passport_photo', 'Passport Size Photo')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
