# Generated by Django 5.0.7 on 2024-08-20 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0008_hr_department_hr_leaverequest_hr_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_leaverequest',
            name='applied_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hr_leaverequest',
            name='employee_id',
            field=models.CharField(default='default_id', max_length=20),
        ),
        migrations.AddField(
            model_name='hr_leaverequest',
            name='reason',
            field=models.TextField(default='No reason provided'),
        ),
        migrations.AddField(
            model_name='hr_leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('On Hold', 'On Hold'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
