# Generated by Django 5.0.7 on 2024-08-20 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0009_hr_leaverequest_applied_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
    ]
