# Generated by Django 5.0.7 on 2024-08-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0010_payrollrequest_delete_payroll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HR_LeaveRequest',
        ),
    ]
