# Generated by Django 5.0.7 on 2024-08-20 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0012_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='applied_on',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='date_applied',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp_app.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.leavetype'),
        ),
    ]
